<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends EntityRepository
{
    public function removeAll()
    {
        return $this->createQueryBuilder('w')
            ->delete()
            ->getQuery()
            ->execute();
    }
}
