# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    word_manager:
        class: AppBundle\Manager\WordManager
        arguments: ["@doctrine.orm.default_entity_manager", "@link_manager"]
    link_manager:
        class: AppBundle\Manager\LinkManager
        arguments: ["@doctrine.orm.default_entity_manager"]
    context.base:
        class: AppBundle\Context\BaseContext
        arguments: ["@word_manager"]
        calls:
            - [setDepth, [2]]
