# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    word_manager:
        class: AppBundle\Manager\WordManager
        arguments: ["@doctrine.orm.default_entity_manager", "@link_manager"]
    link_manager:
        class: AppBundle\Manager\LinkManager
        arguments: ["@doctrine.orm.default_entity_manager"]
    end_strategy.depth:
        class: AppBundle\Strategy\EndStrategy\DepthStrategy
        calls:
            - [setDepth, [2]]
    pulse_strategy.best_link:
        class: AppBundle\Strategy\PulseStrategy\BestLinkStrategy
        arguments: ["@word_manager"]
    init_strategy.best_word:
        class: AppBundle\Strategy\InitStrategy\BestWordStrategy
        arguments: ["@word_manager"]
    context.base:
        class: AppBundle\Context\BaseContext
        arguments: ["@init_strategy.best_word", "@end_strategy.depth", "@pulse_strategy.best_link"]
